.TH spawn-fcgi 1 2009-02-06
.SH NAME
spawn-fcgi \- Spawns FastCGI processes
.SH SYNOPSIS
.B spawn-fcgi
[options] [ -- <fcgiapp> [fcgi app arguments]]

.B spawn-fcgi
\-v

.B spawn-fcgi
\-h
.SH DESCRIPTION
\fIspawn-fcgi\fP is used to spawn remote FastCGI processes (but may be used
for local processes, too).
.SH OPTIONS
\fIspawn-fcgi\fP accepts the following options:
.TP 8
.B  \-f <path>
Filename of the FastCGI application to spawn. If you need to specify
additional arguments, specify the application and its parameters after "--";
this option is ignored if <fcgiapp> is given.
.TP 8
.B  \-a <addr>
IP address to bind to (for TCP/IP-based IPC)
.TP 8
.B  \-p <port>
TCP port to bind to (for TCP/IP-based IPC)
.TP 8
.B  \-s <path>
Path to the Unix-domain socket to bind to (for Unix sockets-based IPC)
.TP 8
.B  \-C <children>
(PHP only) Number of children to spawn by setting the PHP_FCGI_CHILDREN
environment variable. Default is not to overwrite the environment variable;
php will spawn no childs if the var is not set (same as setting it to 0).
.TP 8
.B  \-F <children>
Number of children to fork. Defaults to 1.
.TP 8
.B  \-P <path>
Name of the PID file for spawned processes (ignored in no-fork mode)
.TP 8
.B  \-n
No forking should take place (for daemontools)
.TP 8
.B  \-c <dir>
Chroot to specified directory (can only be invoked by root)
.TP 8
.B  \-u
User ID to change to (can only be invoked by root)
.TP 8
.B  \-g
Group ID to change to (can only be invoked by root). Defaults to primary group
of user if -u is given,
.TP 8
.B  \-?, \-h
General usage instructions
.TP 8
.B  \-v
Shows version information and exits
.SH AUTHOR
This manual page was written by Gunnar Wolf <gwolf@debian.org>, for
the Debian GNU/linux system (but may be used by others).
